### ISSUE TITLE
MISP Tools Manual Import issues with MISP 2.5.2 

### ISSUE THREAD

**Issue by adpaccent** [CrowdStrike/MISP-tools#188]
Hi,

it looks MISP Tools Manual import does not support the latest version of MISP 2.5.2.

[2024-11-25 15:50:51,606] INFO    misp_tools
[2024-11-25 15:50:51,606] INFO    misp_tools    '##::::'##:'####::'######::'########:::::'########::'#######:::'#######::'##::::::::'######::
[2024-11-25 15:50:51,606] INFO    misp_tools     ###::'###:. ##::'##... ##: ##.... ##::::... ##..::'##.... ##:'##.... ##: ##:::::::'##... ##:
[2024-11-25 15:50:51,606] INFO    misp_tools     ####'####:: ##:: ##:::..:: ##:::: ##::::::: ##:::: ##:::: ##: ##:::: ##: ##::::::: ##:::..::
[2024-11-25 15:50:51,606] INFO    misp_tools     ## ### ##:: ##::. ######:: ########:::::::: ##:::: ##:::: ##: ##:::: ##: ##:::::::. ######::
[2024-11-25 15:50:51,606] INFO    misp_tools     ##. #: ##:: ##:::..... ##: ##.....::::::::: ##:::: ##:::: ##: ##:::: ##: ##::::::::..... ##:
[2024-11-25 15:50:51,606] INFO    misp_tools     ##:.:: ##:: ##::'##::: ##: ##:::::::::::::: ##:::: ##:::: ##: ##:::: ##: ##:::::::'##::: ##:
[2024-11-25 15:50:51,606] INFO    misp_tools     ##:::: ##:'####:. ######:: ##:::::::::::::: ##::::. #######::. #######:: ########:. ######::
[2024-11-25 15:50:51,607] INFO    misp_tools    ..:::::..::....:::......:::..:::::::::::::::..::::::.......::::.......:::........:::......:::
[2024-11-25 15:50:51,607] INFO    misp_tools               _____
[2024-11-25 15:50:51,607] INFO    misp_tools                /  '
[2024-11-25 15:50:51,607] INFO    misp_tools             ,-/-,__ __
[2024-11-25 15:50:51,607] INFO    misp_tools            (_/  (_)/ (_
[2024-11-25 15:50:51,607] INFO    misp_tools                         _______                        __ _______ __        __ __
[2024-11-25 15:50:51,607] INFO    misp_tools                        |   _   .----.-----.--.--.--.--|  |   _   |  |_.----|__|  |--.-----.
[2024-11-25 15:50:51,607] INFO    misp_tools                        |.  1___|   _|  _  |  |  |  |  _  |   1___|   _|   _|  |    <|  -__|
[2024-11-25 15:50:51,607] INFO    misp_tools                        |.  |___|__| |_____|________|_____|____   |____|__| |__|__|__|_____|
[2024-11-25 15:50:51,607] INFO    misp_tools                        |:  1   |                         |:  1   |
[2024-11-25 15:50:51,607] INFO    misp_tools                        |::.. . |                         |::.. . |  Threat Intelligence v0.8.0
[2024-11-25 15:50:51,607] INFO    misp_tools                        `-------'                         `-------'
[2024-11-25 15:50:51,607] INFO    misp_tools
/misp/.local/lib/python3.11/site-packages/pymisp/__init__.py:67: FutureWarning: This class is deprecated, use PyMISP instead
  warnings.warn('This class is deprecated, use PyMISP instead', FutureWarning)
[2024-11-25 15:50:52,633] INFO    processor/main       Retrieving all galaxy cluster values for the Android cluster.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/misp/misp_import.py", line 505, in <module>
    main()
  File "/misp/misp_import.py", line 495, in main
    import_handler = ImportHandler(config, intel_api_client,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/misp/misp_import.py", line 312, in __init__
    self.importer = CrowdstrikeToMISPImporter(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/misp/cs_misp_import/importer.py", line 76, in __init__
    self.all_galaxies = self.get_galaxies()
                        ^^^^^^^^^^^^^^^^^^^
  File "/misp/cs_misp_import/importer.py", line 270, in get_galaxies
    all_galaxies.append(self.misp_client.search_galaxy_clusters(gal["id"], searchall=""))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/misp/.local/lib/python3.11/site-packages/pymisp/api.py", line 1781, in search_galaxy_clusters
    clusters_j = self._check_json_response(r)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/misp/.local/lib/python3.11/site-packages/pymisp/api.py", line 3970, in _check_json_response
    r = self._check_response(response, expect_json=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/misp/cs_misp_import/misp_safe_check_response.py", line 55, in safe_check_response
    raise MISPServerError(fail_msg)
pymisp.exceptions.MISPServerError: Error code 500: An Internal Error Has Occurred.
[2024-11-25 15:50:51,607] INFO     config
[2024-11-25 15:50:51,607] INFO     config  _______ _     _ _______ _______ _     _      _______  _____  __   _ _______ _____  ______
[2024-11-25 15:50:51,607] INFO     config  |       |_____| |______ |       |____/       |       |     | | \  | |______   |   |  ____
[2024-11-25 15:50:51,607] INFO     config  |_____  |     | |______ |_____  |    \_      |_____  |_____| |  \_| |       __|__ |_____|
[2024-11-25 15:50:51,607] INFO     config
[2024-11-25 15:50:52,015] INFO     config  No configuration errors found
[2024-11-25 15:50:52,015] INFO     config
[2024-11-25 15:50:52,015] INFO     config  ____ _  _ ____ ____ _  _ ____    ___  ____ ____ ____ ____ ___
[2024-11-25 15:50:52,015] INFO     config  |    |__| |___ |    |_/  [__     |__] |__| [__  [__  |___ |  \
[2024-11-25 15:50:52,015] INFO     config  |___ |  | |___ |___ | \_ ___]    |    |  | ___] ___] |___ |__/
[2024-11-25 15:50:52,015] INFO     config

Instead no any issues with MISP 2.5.1.
Could you please help me?

Please let me know.

Thanks

**Comment by adpaccent** [comment]
Hi,

do you please have any news?
The following one is the ticket on MISP project side:

https://github.com/MISP/MISP/issues/10062

Thanks
