### ISSUE TITLE
220811 Version - Fails with TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by packet-rat** [CrowdStrike/MISP-tools#29]
### python3 misp_import.py --reports --actors

```

[[2022-08-12 16:23:12,268] (INFO) 
<SNIP>
[2022-08-12 16:23:32,454] (INFO) 
 ______  _______  ______ _____ __   _      _____ _______  _____   _____   ______ _______
 |_____] |______ |  ____   |   | \  |        |   |  |  | |_____] |     | |_____/    |
 |_____] |______ |_____| __|__ |  \_|      __|__ |  |  | |       |_____| |    \_    |

[2022-08-12 16:23:32,454] (INFO) 


[2022-08-12 16:23:32,454] (INFO) Started getting adversaries from Crowdstrike Intel API and pushing them as events in MISP.
[2022-08-12 16:24:12,502] (ERROR) unsupported operand type(s) for +=: 'int' and 'NoneType'
Traceback (most recent call last):
  File "misp_import.py", line 213, in main
    importer.import_from_crowdstrike(int(settings["CrowdStrike"]["init_reports_days_before"]),
  File "/home/rx118r/src/crowdstrike/220812/MISP-tools-main/cs_misp_import/importer.py", line 143, in import_from_crowdstrike
    self.actors_importer.process_actors(actors_days_before, self.event_ids)
  File "/home/rx118r/src/crowdstrike/220812/MISP-tools-main/cs_misp_import/actors.py", line 114, in process_actors
    actors = self.intel_api_client.get_actors(start_get_events)
  File "/home/rx118r/src/crowdstrike/220812/MISP-tools-main/cs_misp_import/intel_client.py", line 119, in get_actors
    offset += resp_json.get('meta', {}).get('pagination', {}).get('limit')
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
unsupported operand type(s) for +=: 'int' and 'NoneType'
](url)
```

**Comment by jshcodes** [comment]
This appears as if you were returned an empty element in the pagination branch for actors.  Can you tell me what your actors import setting was set for?  I'm able to pull ~ 185 by setting my days before to 365.  (Will add a check for this in the code regardless, but would like to be able to reliably recreate the issue.)

**Comment by packet-rat** [comment]
External Connectivity from our dev lab was lost earlier today just as I as beginning to test the new code.  So I’m dead-in-the-water
________________________________

**Comment by jshcodes** [comment]
Boooooo!

Ok. Well we should definitely check the datatype received from the API before trying to use it in a calculation regardless, so I'll wrap this in a check and have you retest when connectivity is restored.  😀
