### ISSUE TITLE
Question: Where do I find the logs to review what may have cause below issue

### ISSUE THREAD

**Issue by rajnishmatta** [CrowdStrike/MISP-tools#71]
Hi there,

The new update of processing Indicator type works great! but currently facing issue with ingesting cobaltstrike events. This has happened every time.
I have tried rebooting MISP and using fresh build of misp-tools. 

![cobaltstike_error](https://user-images.githubusercontent.com/7588330/203983129-12cb065a-338e-4a2b-8e42-320a90538d5a.png)

**Comment by rajnishmatta** [comment]
started to appear for more indicator types

![image](https://user-images.githubusercontent.com/7588330/204117036-3b3477e1-41f9-4868-b6ff-45aa00f68d1b.png)

**Comment by jshcodes** [comment]
This message means we submitted the update and a couple of minutes, timed out. Typically I see this when the MISP server is getting overload but a formatting issue in the event could also be causing it.  Are you seeing anything in the MISP server log (`/var/www/MISP/app/tmp/logs/`)?

**Comment by rajnishmatta** [comment]
**got error logs and resque logs. Looks like the server is overloaded. appears to be memory issue.**

will close this one. appreciate your time.


2022-11-27 13:17:17 Warning: Warning (2): trim() expects parameter 1 to be string, array given in [/var/www/MISP/app/Controller/SightingsController.php, line 65]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
trim - [internal], line ??
SightingsController::add() - APP/Controller/SightingsController.php, line 65
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-11-27 13:17:56 Warning: Warning (2): trim() expects parameter 1 to be string, array given in [/var/www/MISP/app/Controller/SightingsController.php, line 65]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
trim - [internal], line ??
SightingsController::add() - APP/Controller/SightingsController.php, line 65
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-11-27 13:17:57 Warning: Warning (2): trim() expects parameter 1 to be string, array given in [/var/www/MISP/app/Controller/SightingsController.php, line 65]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
trim - [internal], line ??
SightingsController::add() - APP/Controller/SightingsController.php, line 65
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-11-27 13:17:57 Warning: Warning (2): trim() expects parameter 1 to be string, array given in [/var/www/MISP/app/Controller/SightingsController.php, line 65]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
trim - [internal], line ??
SightingsController::add() - APP/Controller/SightingsController.php, line 65
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-11-27 13:32:18 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 36864 bytes) in [/var/www/MISP/app/Lib/Tools/JsonTool.php, line 39]
2022-11-27 13:32:18 Error: [InternalErrorException] Internal Server Error
Request URL: /events/edit/b29aec5c-8708-4aaa-b77c-808c7806d7fc
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2022-11-27 13:33:18 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 1121976352 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeRequest.php, line 1106]
2022-11-27 13:33:18 Error: [InternalErrorException] Internal Server Error
Request URL: /events/edit/b29aec5c-8708-4aaa-b77c-808c7806d7fc
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2022-11-27 13:33:50 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 1105199136 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeRequest.php, line 1106]
2022-11-27 13:33:50 Error: [InternalErrorException] Internal Server Error
Request URL: /events/edit/b29aec5c-8708-4aaa-b77c-808c7806d7fc
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2022-11-27 13:33:59 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 12288 bytes) in [/var/www/MISP/app/Lib/Tools/JsonTool.php, line 39]
2022-11-27 13:33:59 Error: [InternalErrorException] Internal Server Error
Request URL: /events/edit/c38780d2-ee54-407a-a417-9de21dd993c9
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2022-11-27 13:35:07 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/Tools/JsonTool.php, line 39]
2022-11-27 13:35:07 Error: [InternalErrorException] Internal Server Error
Request URL: /events/edit/c38780d2-ee54-407a-a417-9de21dd993c9
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2022-11-27 13:37:04 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 1073741856 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeRequest.php, line 1106]
2022-11-27 13:37:04 Error: [InternalErrorException] Internal Server Error
Request URL: /events/edit/c38780d2-ee54-407a-a417-9de21dd993c9
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
